kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  image: kindest/node:v1.32.5

- role: worker
  image: kindest/node:v1.32.5
  extraPortMappings:
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443

- role: worker
  image: kindest/node:v1.32.5
  extraPortMappings:
    - containerPort: 8080
      hostPort: 8081        # Different host port to avoid conflicts
    - containerPort: 80
      hostPort: 8080
    - containerPort: 443
      hostPort: 8443