apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ops-team-rolebinding
subjects:
- kind: Group
  name: ops-team@example.com  # Azure AD group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ops-team-role
  apiGroup: rbac.authorization.k8s.io