apiVersion: v1
kind: Pod
metadata:
  name: critical-priority-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "512Mi"
        cpu: "1500m"
  priorityClassName: high-priority