apiVersion: v1
kind: Secret
metadata:
  name: fastapi-db-secret
  namespace: stage-1-practicals
  labels:
    app: fastapi-app
    component: database
type: Opaque
data:
  # Database credentials (base64 encoded)
  db-username: YWRtaW4=          # admin
  db-password: U3VwZXJTZWNyZXQxMjM=  # SuperSecret123
  db-host: bG9jYWxob3N0        # localhost

  # API keys
  api-key: YWJjZGVmZ2hpams=      # abcdefghijk
 
  # JWT secret
  jwt-secret: bXlfc3VwZXJfc2VjcmV0X2p3dF9rZXk=  # my_super_secret_jwt_key

