apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 5    # tells K8 how long it should wait until it creates the next pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1   # max num (or percentage) of pods above the specified replicas count
      maxUnavailable: 1  # declares the max num (or percentage) of unavailable pods during the update
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.0
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /         # GET request to http://pod-ip:80/ on port: 80
            port: 80
          initialDelaySeconds: 5    # specifies how long the probe has to wait to start after the container starts/ Wait 5 seconds after container starts
          periodSeconds: 5        # time between two probes/ Check every 5 seconds, default=10 secs
          successThreshold: 1   # min successful probes after a failed one for the entire process/ 1 successful response = pod is ready