apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql-db

spec:
  clusterIP: None
  selector:
    app: mysql
    
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306