apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: mysql-db

spec:
  serviceName: mysql-svc
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 500Mi
        env:
        - name: MYSQL_ROOT_PASSWORD       # standard MySQL env var
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: MYSQL_ROOT_PASSWORD      # standard MySQL env var

        - name: MYSQL_DATABASE              # standard MySQL env var
          valueFrom:
            configMapKeyRef:
              name: mysql-db-config-map
              key: MYSQL_DATABASE           # standard MySQL env var

        volumeMounts:
        - name: mysql-db-data
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi