apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-actions-self-hosted-calc-app-deployment
  labels:
    app: self-hosted-calc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: self-hosted-calc-app
  template:
    metadata:
      labels:
        app: self-hosted-calc-app
    spec:
      containers:
      - name: self-hosted-calc-app-app
        image: 315183407444.dkr.ecr.ap-south-1.amazonaws.com/gh-actions-self-hosted-calc-app:main-58a9a-29-Apr-25
      imagePullSecrets:
      - name: ecr-registry-secret     # Reference the secret